// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rijvidluwvzvatoarqoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpanZpZGx1d3Z6dmF0b2FycW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Njc0MTAsImV4cCI6MjA3MTE0MzQxMH0.Wm2aXhLV6ZO8ZeSpWwzdskisV_VIQbQvaHmHk0CLVTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});